CREATE SCHEMA TESTDATBASE;

SET SCHEMA TESTDATABASE;

CREATE TABLE PEOPLE (
	IDENTITY_UID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	IDENTITY_DISPLAYNAME VARCHAR(255), 
	IDENTITY_EMAIL VARCHAR(255), 
	IDENTITY_BIRTHDATE DATE
)

ALTER TABLE PEOPLE ADD CONSTRAINT PEOPLE_PK PRIMARY KEY(IDENTITY_UID);
